# Generated by Django 5.2.8 on 2025-11-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
    ]
